=== lyubolp/XML-Course-FMI/3/1.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
   <xs:element name="collection">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="description">
                <xs:complexType>
                    <xs:sequence>
                        <xs:any minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="recipe">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="title" type="xs:string" />
                        <xs:element name="ingredient" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="preparation" minOccurs="0" maxOccurs="1">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="step" type="xs:string" minOccurs="0" maxOccurs="unbounded">
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                                        <xs:attribute name="name" type="xs:string" use="required"/>
                                        <xs:attribute name="amount" type="xs:string"/>
                                        <xs:attribute name="unit" type="xs:string"/>
                                
                            </xs:complexType>
                        </xs:element>

                        <xs:element name="preparation">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="step" type="xs:string" minOccurs="0" maxOccurs="unbounded">
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                        <xs:element name="comment" type="xs:string">
                        </xs:element>

                        <xs:element name="nutrition">
                            <xs:complexType>
                                <xs:attribute name="protein" type="xs:string" use="required"/>
                                <xs:attribute name="carbohydrates" type="xs:string" use="required"/>
                                <xs:attribute name="fat" type="xs:string" use="required"/>
                                <xs:attribute name="calories" type="xs:string" use="required"/>
                                <xs:attribute name="alcohol" type="xs:string" use="optional"/>
                            </xs:complexType>
                        </xs:element>

                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        </xs:complexType>
   </xs:element>
</xs:schema>

=== lyubolp/XML-Course-FMI/3/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="1.xsd">
    <description>
    </description>
    <recipe>
        <title> bar </title>
        <ingredient name="foo" amount="2" unit="bar"></ingredient>
        <preparation>
            <step>Cook it</step>
        </preparation>
        <comment>asd</comment>
        <nutrition protein="1" carbohydrates="1" fat="1" calories="1" alcohol="1"/>
    </recipe>
</collection>
